repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]
        exclude: ^(tests/|examples/|scripts/|development/|tools/)

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]
        exclude: ^(tests/|examples/|scripts/|development/|tools/)

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        args: [--config=.flake8]
        exclude: ^(tests/|examples/|demos/|scripts/|development/|tools/)

  # Temporarily disabled due to type checking issues
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.5.1
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-PyYAML, types-click, types-setuptools]
  #       args: [--ignore-missing-imports]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [--skip, B110]
        exclude: ^(tests/|examples/|scripts/|development/|tools/)
        additional_dependencies: [pbr]

  # Documentation validation is handled by CI workflow (docs-check job)
  # Jekyll requires Ruby/bundle which may not be available in all environments

  # Comprehensive CI validation (optional - uncomment to enable)
  - repo: local
    hooks:
      - id: comprehensive-ci-test
        name: comprehensive-ci-test
        entry: ./scripts/local-ci-test.sh
        language: system
        pass_filenames: false
        always_run: true
        verbose: true

default_language_version:
  python: python3

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
