# Pre-commit hooks configuration for ADRI batch processing system
#
# This file defines hooks that can be used by other repositories
# that want to integrate ADRI's flake8 batch processing system

-   id: flake8-batch-fix
    name: Flake8 Batch Processor
    description: Fix flake8 errors using intelligent batch processing to prevent interface overload
    entry: python fix_flake8_issues.py --legacy
    language: system
    types: [python]
    stages: [pre-commit]
    verbose: true
    pass_filenames: false
    
-   id: flake8-batch-check
    name: Flake8 Batch Check
    description: Check for flake8 errors with batch processing compatibility
    entry: python -m flake8 --config=development/config/.flake8
    language: system
    types: [python]
    stages: [pre-commit]
    verbose: true
    pass_filenames: false
    
-   id: flake8-batch-analyze
    name: Flake8 Error Analyzer
    description: Analyze and categorize flake8 errors for batch processing
    entry: python development/tools/scripts/core/error_categorizer.py
    language: system
    types: [python]
    stages: [manual]
    verbose: true
    pass_filenames: false
