# ADRI Standards Meta-Schema
# Defines the structure that all ADRI standards must follow

standards:
  id: adri_meta_schema
  name: ADRI Standards Meta-Schema
  version: 1.0.0
  authority: ADRI Framework
  description: Meta-schema defining the structure of valid ADRI standards

schema_definition:
  required_sections:
    - standards
    - requirements

  standards_section:
    required_fields:
      - id
      - name
      - version
      - authority
    optional_fields:
      - description
      - effective_date
      - expires_date
      - tags

    field_constraints:
      id:
        type: string
        pattern: "^[a-zA-Z0-9_]+_standard$"
        description: Must end with '_standard'
      name:
        type: string
        min_length: 5
        max_length: 100
      version:
        type: string
        pattern: "^\\d+\\.\\d+\\.\\d+.*$"
        description: Must follow semantic versioning
      authority:
        type: string
        min_length: 3
        max_length: 100

  requirements_section:
    required_fields:
      - overall_minimum
    optional_fields:
      - field_requirements
      - dimension_requirements

    field_constraints:
      overall_minimum:
        type: number
        min_value: 0
        max_value: 100
        description: Overall minimum score requirement

  field_requirements_section:
    allowed_field_types:
      - string
      - integer
      - float
      - boolean
      - date
      - datetime

    allowed_constraints:
      string:
        - nullable
        - pattern
        - min_length
        - max_length
        - allowed_values
      integer:
        - nullable
        - min_value
        - max_value
        - allowed_values
      float:
        - nullable
        - min_value
        - max_value
      boolean:
        - nullable
      date:
        - nullable
        - after_date
        - before_date
      datetime:
        - nullable
        - after_datetime
        - before_datetime

  dimension_requirements_section:
    allowed_dimensions:
      - validity
      - completeness
      - consistency
      - freshness
      - plausibility

    dimension_constraints:
      minimum_score:
        type: number
        min_value: 0
        max_value: 20
        description: Minimum score for this dimension

validation_rules:
  - rule: "standards section must be present"
    check: "has_section('standards')"
  - rule: "requirements section must be present"
    check: "has_section('requirements')"
  - rule: "overall_minimum must be between 0-100"
    check: "0 <= requirements.overall_minimum <= 100"
  - rule: "dimension scores must be between 0-20"
    check: "all(0 <= score <= 20 for score in dimension_requirements.*.minimum_score)"
  - rule: "field types must be valid"
    check: "all(field.type in allowed_field_types for field in field_requirements.*)"
