name: Branch Validation - Issue-First Development

on:
  push:
    branches-ignore: [main, develop, master]  # Skip main branches

jobs:
  validate-branch:
    name: Validate Issue-First Branch Name
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Validate branch naming convention
        run: |
          BRANCH="${{ github.ref_name }}"
          
          echo "🔍 Validating branch name: $BRANCH"
          echo "Required format: type/issue-{number}-description"
          
          # Required format: type/issue-{number}-description
          if [[ ! "$BRANCH" =~ ^(feat|fix|docs|chore|enhance|hotfix|refactor|test|style|perf)/issue-[0-9]+-.*$ ]]; then
            echo ""
            echo "❌ BRANCH REJECTED: Invalid naming convention"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo "✅ Required format: type/issue-{number}-description"
            echo ""
            echo "📋 Valid types:"
            echo "  • feat      - New features"
            echo "  • fix       - Bug fixes"
            echo "  • docs      - Documentation changes"
            echo "  • enhance   - Enhancements to existing features"
            echo "  • hotfix    - Emergency fixes"
            echo "  • refactor  - Code refactoring"
            echo "  • test      - Test additions or modifications"
            echo "  • chore     - Maintenance tasks"
            echo "  • style     - Code style changes"
            echo "  • perf      - Performance improvements"
            echo ""
            echo "🎯 Examples:"
            echo "  • feat/issue-123-user-authentication"
            echo "  • fix/issue-456-memory-leak"
            echo "  • docs/issue-789-api-documentation"
            echo "  • enhance/issue-321-performance-improvement"
            echo ""
            echo "📍 Current branch: $BRANCH"
            echo ""
            echo "🔧 To fix this:"
            echo "1. Create a GitHub issue for your work: https://github.com/adri-standard/adri/issues/new/choose"
            echo "2. Rename your branch: git branch -m type/issue-{number}-description"
            echo "3. Push again: git push -u origin HEAD"
            echo ""
            echo "ℹ️  Need help? See: https://github.com/adri-standard/adri/blob/main/CONTRIBUTING.md"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            exit 1
          fi
          
          # Extract issue number for validation
          ISSUE_NUM=$(echo "$BRANCH" | grep -o 'issue-[0-9]\+' | grep -o '[0-9]\+')
          
          echo "✅ Branch name follows issue-first convention"
          echo "📋 Linked to issue #$ISSUE_NUM"
          echo "🎯 Branch type: $(echo "$BRANCH" | cut -d'/' -f1)"

      - name: Add helpful comment for successful validation
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            const issueNum = branch.match(/issue-(\d+)/)?.[1];
            
            if (issueNum) {
              console.log(`✅ Branch ${branch} correctly links to issue #${issueNum}`);
              console.log('🚀 Issue-first development validated - proceeding with CI pipeline');
            }

  # This job provides clear feedback but doesn't block other CI
  validation-summary:
    name: ✅ Issue-First Validation Complete
    if: always()
    needs: [validate-branch]
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Report validation status
        run: |
          echo "📊 Branch Validation Results:"
          echo "Branch Naming: ${{ needs.validate-branch.result }}"
          
          if [[ "${{ needs.validate-branch.result }}" != "success" ]]; then
            echo ""
            echo "❌ Issue-first development validation failed"
            echo "🔄 This branch cannot proceed until naming is corrected"
            echo ""
            echo "💡 Quick fix: Rename branch to include issue number"
            echo "   Example: git branch -m feat/issue-123-your-feature"
            exit 1
          fi
          
          echo ""
          echo "✅ Issue-first development validated!"
          echo "🚀 Proceeding with standard CI pipeline"
