name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for setuptools_scm

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,test]

    - name: Run pre-commit checks
      run: |
        pre-commit run --all-files

    - name: Run tests with pytest
      run: |
        pytest --cov=adri --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install -e .[security]

    - name: Run Bandit security scan
      run: |
        bandit -r src/ -f json -o bandit-report.json --skip B110
        bandit -r src/ --skip B110

    - name: Run Safety check
      run: |
        safety check

    - name: Run pip-audit
      run: |
        pip-audit

  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for setuptools_scm

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build twine setuptools_scm

    - name: Test setuptools_scm version detection
      run: |
        python -c "from setuptools_scm import get_version; print(f'Version: {get_version()}')"

    - name: Build package
      run: |
        python -m build

    - name: Check package
      run: |
        twine check dist/*

    - name: Test installation
      run: |
        pip install dist/*.whl
        adri --version
        python -c "import adri; print(f'ADRI version: {adri.__version__}')"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ github.run_number }}
        path: dist/

  cleanup:
    runs-on: ubuntu-latest
    needs: [test, security, build-test]
    if: always()  # Run cleanup even if some jobs fail

    steps:
    - uses: actions/checkout@v4

    - name: Clean up temporary CI artifacts
      run: |
        echo "🧹 Cleaning up temporary CI artifacts for structure validation..."

        # Remove all possible temporary artifacts generated during CI
        rm -rf coverage.* .coverage* htmlcov/ .pytest_cache/ .benchmarks/
        rm -rf build/ dist/ *.egg-info/ .tox/ .mypy_cache/ .hypothesis/
        rm -rf bandit-report.* *.tmp *.temp pip-*.log
        rm -rf __pycache__/ .DS_Store Thumbs.db

        echo "✅ Cleanup completed - environment ready for structure validation"

        # Show final clean directory state
        echo "📊 Final root directory contents:"
        ls -la | grep -E "^(d|-)" | awk '{print "   " $9}' | grep -v "^\.$" | grep -v "^\.\.$$"

  validate-root-structure:
    runs-on: ubuntu-latest
    needs: [cleanup]
    if: always()  # Run even if cleanup had issues

    steps:
    - uses: actions/checkout@v4

    - name: Validate root directory structure
      run: |
        echo "🔍 Validating repository root directory structure..."

        # Define allowed root files
        ALLOWED_FILES=(
          ".commitlintrc.json"
          ".flake8"
          ".gitignore"
          ".gitmessage"
          ".pre-commit-config.yaml"
          "adri-config.yaml"
          "ARCHITECTURE.md"
          "CHANGELOG.md"
          "CONTRIBUTING.md"
          "LICENSE"
          "pyproject.toml"
          "README.md"
          "SECURITY.md"
        )

        # Define allowed root directories
        ALLOWED_DIRS=(
          ".git"
          ".github"
          "archive"
          "demos"
          "docs"
          "examples"
          "scripts"
          "src"
          "tests"
        )

        # Check for unauthorized files in root (excluding temporary test artifacts)
        echo "📁 Checking for unauthorized files in root directory..."
        VIOLATIONS=0

        for file in *; do
          # Skip temporary test artifacts that might be created during parallel CI runs
          if [[ "$file" =~ ^(htmlcov|\.coverage.*|coverage\.(json|xml)|\.pytest_cache|\.benchmarks|.*_standard\.yaml|test_logs|bandit-report\.(json|xml)|\.tox|\.mypy_cache|\.hypothesis|.*\.tmp|.*\.temp|pip-.*\.log|build|dist|.*\.egg-info)$ ]]; then
            echo "⏭️ Skipping temporary artifact: $file"
            continue
          fi
          if [[ -f "$file" ]]; then
            # Check if file is in allowed list
            FOUND=0
            for allowed in "${ALLOWED_FILES[@]}"; do
              if [[ "$file" == "$allowed" ]]; then
                FOUND=1
                break
              fi
            done

            if [[ $FOUND -eq 0 ]]; then
              echo "❌ UNAUTHORIZED FILE: $file"
              echo "   Should be moved to appropriate directory:"

              # Suggest proper location based on file type
              case "$file" in
                *.md)
                  if [[ "$file" == *"plan"* || "$file" == *"implementation"* || "$file" == *"guide"* ]]; then
                    echo "   → archive/internal-docs/ (internal documentation)"
                  else
                    echo "   → docs/ (user documentation)"
                  fi
                  ;;
                *.py)
                  echo "   → tests/ (test files) or examples/ (example code)"
                  ;;
                *.json|*.xml|*.report)
                  echo "   → Should be in .gitignore (build artifacts)"
                  ;;
                *.yaml|*.yml)
                  if [[ "$file" != "adri-config.yaml" ]]; then
                    echo "   → examples/standards/ (data standards) or tests/fixtures/ (test data)"
                  fi
                  ;;
                *)
                  echo "   → Check if this file should exist or be gitignored"
                  ;;
              esac
              VIOLATIONS=$((VIOLATIONS + 1))
            fi
          elif [[ -d "$file" ]]; then
            # Check if directory is in allowed list
            FOUND=0
            for allowed in "${ALLOWED_DIRS[@]}"; do
              if [[ "$file" == "$allowed" ]]; then
                FOUND=1
                break
              fi
            done

            if [[ $FOUND -eq 0 ]]; then
              echo "❌ UNAUTHORIZED DIRECTORY: $file"
              echo "   Consider if this should be:"
              echo "   → Moved inside src/, tests/, docs/, or examples/"
              echo "   → Added to .gitignore if it's a build artifact"
              echo "   → Archived if it's legacy/internal content"
              VIOLATIONS=$((VIOLATIONS + 1))
            fi
          fi
        done

        # Report results
        if [[ $VIOLATIONS -eq 0 ]]; then
          echo "✅ Root directory structure is clean and compliant!"
          echo ""
          echo "📊 Current root structure:"
          ls -la | grep -E "^(d|-)" | awk '{print "   " $9}' | grep -v "^\.$" | grep -v "^\.\.$$"
        else
          echo ""
          echo "❌ Found $VIOLATIONS structure violations!"
          echo ""
          echo "📋 Clean root directory policy:"
          echo "   • Documentation: README.md, CHANGELOG.md, CONTRIBUTING.md, etc."
          echo "   • Configuration: pyproject.toml, .gitignore, .pre-commit-config.yaml"
          echo "   • Source directories: src/, tests/, docs/, examples/, demos/"
          echo "   • NO: Planning docs, build artifacts, temp files, AI-generated files"
          echo ""
          echo "🛠️  To fix violations:"
          echo "   1. Move files to appropriate directories (see suggestions above)"
          echo "   2. Add build artifacts to .gitignore"
          echo "   3. Archive internal documentation to archive/internal-docs/"
          echo ""
          exit 1
        fi

  validate-gitignore-protection:
    runs-on: ubuntu-latest
    needs: [cleanup]
    if: always()  # Run even if cleanup had issues

    steps:
    - uses: actions/checkout@v4

    - name: Validate .gitignore protections
      run: |
        echo "🛡️ Validating .gitignore protection patterns..."

        # Required protection patterns
        REQUIRED_PATTERNS=(
          "archive/"
          "src/adri/_version.py"
          "*_plan.md"
          "*_implementation*.md"
          "*.DS_Store"
          "*.swp"
          "bandit-report.json"
          "coverage.xml"
          "dist/"
          "build/"
          "*.egg-info/"
        )

        MISSING_PATTERNS=()

        for pattern in "${REQUIRED_PATTERNS[@]}"; do
          if ! grep -qF "$pattern" .gitignore; then
            MISSING_PATTERNS+=("$pattern")
          fi
        done

        if [[ ${#MISSING_PATTERNS[@]} -eq 0 ]]; then
          echo "✅ All required protection patterns are present in .gitignore"
        else
          echo "❌ Missing required .gitignore patterns:"
          for pattern in "${MISSING_PATTERNS[@]}"; do
            echo "   - $pattern"
          done
          echo ""
          echo "These patterns help prevent accidental publication of:"
          echo "   • Build artifacts and temporary files"
          echo "   • AI-generated planning documents"
          echo "   • System files and caches"
          echo "   • Internal development artifacts"
          exit 1
        fi
