name: Conventional Commits

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install commitlint
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Validate Conventional Commits
        run: |
          echo "🔍 Validating commit messages..."
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # Get commits in PR
            git log --format="%H %s" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} > commits.txt

            # Check each commit
            while IFS= read -r line; do
              commit_hash=$(echo "$line" | cut -d' ' -f1)
              commit_msg=$(echo "$line" | cut -d' ' -f2-)
              echo "Checking commit: $commit_hash - $commit_msg"
              echo "$commit_msg" | npx commitlint --config .commitlintrc.json || {
                echo "❌ Commit message does not follow conventional commits format: $commit_msg"
                exit 1
              }
            done < commits.txt

            echo "✅ All commit messages follow conventional commits format"
          fi

      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
          disallowScopes: |
            release
