name: Prepare Release Drafts

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"

jobs:
  prepare-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for commit analysis

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub requests

    - name: Generate release candidates
      id: generate
      run: |
        python scripts/prepare_releases.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}

    - name: Summary
      run: |
        echo "✅ Release preparation completed"
        echo "📋 Check GitHub Releases for updated draft releases"
        echo "🚀 Ready to publish when you're ready to release"
